debug this garbaggio

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,8 +25,8 @@ jobs:
           if [[ "${{ github.event.release.tag_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
             echo "Valid release tag. Continue with the workflow."
           else
-            echo "Invalid release tag. Exiting gracefully."
-            exit 0  # Exit without an error
+            echo "Invalid release tag."
+            exit 1
           fi
   verify_manifest:
     runs-on: ubuntu-latest
@@ -36,7 +36,9 @@ jobs:
       - name: Check that version matches
         run: |
           versionwithoutv=$(echo ${{github.event.release.tag_name}} | cut -d 'v' -f 2)
-          if [[ "$(jq -r '.version_number' $(find ./${{env.name}}/Package -name ${{env.jsonf}}))" != $versionwithoutv ]]; then
+          versionfrommanifest="$(jq -r '.version_number' $(find ./${{env.name}}/Package -name ${{env.jsonf}}))"
+          echo "tag_name=${{github.event.release.tag_name}} versionwithoutv=$versionwithoutv versionfrommanifest=$versionfrommanifest"
+          if [[ $versionfrommanifest != $versionwithoutv ]]; then
             echo "::debug::${{github.event.release.tag_name}}"
             echo "::debug::$(cat $(find ./ -name ${{env.jsonf}}))"
             echo "::error::Version in ${{env.jsonf}} does not match tag version"
