add some debugging

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,8 +1,6 @@
-name: Publish package
+name: CI Publish package
 
 on:
-  release:
-    types: [published] # run when a new release is published
   workflow_run:
     workflows: ["build"] # run if build.yml is successfully completed
     types:
@@ -25,10 +23,10 @@ jobs:
         run: |
           version=$(grep -Po "AssemblyVersion\(\"\K([0-9]+\.[0-9]+\.[0-9]+)" ${{env.name}}/Properties/AssemblyInfo.cs)
           versionfrommanifest="$(jq -r '.version_number' $(find ./${{env.name}}/Package -name ${{env.jsonf}}))"
+          [ -z "$version" ] && echo "::error::version is empty!" && exit 1
+          [ -z "$versionfrommanifest" ] && echo "::error::versionfrommanifest is empty!" && exit 1
           if [[ $versionfrommanifest != $version ]]; then
-            echo "::debug::${{github.event.release.tag_name}}"
-            echo "::debug::$(cat $(find ./ -name ${{env.jsonf}}))"
-            echo "::error::Version in ${{env.jsonf}} does not match tag version"
+            echo "::error::Version in ${{env.jsonf}} does not match assembly version"
             exit 1
           fi
           echo "VERSION=${version}" >> $GITHUB_ENV
